version: '3.8'

services:
  app:
    container_name: clients-crm
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db

